### ISSUE TITLE
Asynchronous Lectures/Labs/Tutorials "TBA"

### ISSUE THREAD

**Issue by nafung** [FlyteWizard/UVicSchedule#3]
The script fails for a class with an asynchronous lecture, but a scheduled lab.  Specifically, ECE 241.  Output pasted below.

```Traceback (most recent call last):
  File ".\getSchedule.py", line 227, in <module>
    main()
  File ".\getSchedule.py", line 152, in main
    time_range = [datetime.datetime.strptime(time.strip(), "%I:%M %p") for time in time_soup[1].text.split("-")]
  File ".\getSchedule.py", line 152, in <listcomp>
    time_range = [datetime.datetime.strptime(time.strip(), "%I:%M %p") for time in time_soup[1].text.split("-")]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'TBA' does not match format '%I:%M %p'```

**Comment by FlyteWizard** [comment]
@kenmuir I guess the expected output would be to "skip" lectures/labs/tutorials that have a TBA time slot and not include them in the .ics file.

**Comment by nafung** [comment]
edited output for formatting.

skipping event creation for a TBA time sounds like the best option, with the alternative being the creation of an 3-month long event for the course, which will make for a messy .ics file.

**Comment by FlyteWizard** [comment]
Deployed a fix, but I do not have any asynchronous courses, so can't be certain.

**Comment by nafung** [comment]
No errors, I'd say its a success.
